repos:
  - repo: https://github.com/sdispater/poetry-export
    rev: v0.4.1
    hooks:
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
